# Generated by Django 4.2.1 on 2023-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_icon_url',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_video_url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_name',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='gheaven.genre'),
        ),
    ]
