# Generated by Django 4.2.1 on 2023-07-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0003_alter_game_icon_url_alter_game_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_icon_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_url',
            field=models.TextField(),
        ),
    ]
