# Generated by Django 4.2.1 on 2023-07-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0005_remove_app_app_url_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_time',
            field=models.TimeField(),
        ),
    ]
