# Generated by Django 4.2.1 on 2023-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0007_alter_order_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='remaining_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pc',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
