# Generated by Django 4.2.1 on 2023-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0009_alter_pc_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='remaining_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
