# Generated by Django 4.2.1 on 2023-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0011_alter_user_remaining_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], max_length=20),
        ),
    ]
