# Generated by Django 4.2.1 on 2023-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0013_alter_order_total_time_alter_pc_remaining_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remaining_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_coins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
