# Generated by Django 4.2.1 on 2023-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0015_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon_url',
            field=models.FileField(upload_to=''),
        ),
    ]
