# Generated by Django 4.2.1 on 2023-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0016_alter_game_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_url',
            field=models.FileField(upload_to=''),
        ),
    ]
