# Generated by Django 4.2.1 on 2023-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0017_alter_game_url_alter_game_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_icon_url',
            field=models.FileField(upload_to=''),
        ),
    ]
