# Generated by Django 4.2.1 on 2023-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0024_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
