# Generated by Django 4.2.1 on 2023-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0026_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
