# Generated by Django 4.2.1 on 2023-07-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gheaven', '0027_alter_activity_end_time_alter_activity_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration',
        ),
    ]
